-- CREATE DATABASE IF NOT EXISTS
-- CREATE SCHEMA IF NOT EXISTS rewards;

CREATE TABLE retailer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName CHARACTER(40),
    lastName CHARACTER(40),
    email CHARACTER(40)
);
CREATE TABLE point (
    id BIGINT,  -- primary
    retailerId BIGINT, -- secondary
    entryTime TIMESTAMP,
    points INTEGER
);